#!/usr/bin/env bash
"""
Transfers a file from our client to a server: Accepting 4 parameters
"""

IF [ $# -It 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1

f1

path_2_file=$1
server_ip=$2
username=$3
ssh_key=$4

scp -0 StrictHostKeyChecking=OO -i "$ssh_key" "$path_2_file" "$username"@"server_ip":~/
