#!/usr/bin/env bash
"""
Install nginx on web-01,Nginx should be listening on port 80, querying Nginx at its root / it must return a page that contains the string Hello World!, nginx redirection
"""

apt.get update -y
apt.get install nginx -y
sudo ufw allow 'nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/& rewrite ^/redirect_me https://https://www.linkedin.com/@wisetaught permanent; /etc/nginx/sites-available/default
service nginx restart
