#!/usr/bin/env bash
# Displays  type of network a computer in local is connected to
#  Displays type of network could connect an office in one building to another office in a building a few streets away
#  Displays What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)

3
2
1
